#!/bin/bash


# List All Logs with Priority ERROR
journalctl -p err..alert

# Install MySQL Server
sudo apt-get update
sudo apt-get install mysql-server

# Logs Generated by MySQL
journalctl -u mysqld.service

# Install Nginx and Display Nginx Logs
sudo apt-get install nginx
sudo cat /var/log/nginx/access.log

# Create todo-list.txt
touch ~/todo-list.txt

# Add user "accounting"
sudo useradd accounting

# Change Group Ownership of todo-list.txt
sudo chgrp accounting ~/todo-list.txt

# Generate RSA Key Pair
ssh-keygen -t ed25519

# Install openssh-server
sudo apt install -y openssh-server
sudo systemctl enable ssh
sudo systemctl start ssh

# Run the ssh-audit tool
git clone https://github.com/arthepsy/ssh-audit
cd ssh-audit
python3 ssh-audit.py 127.0.0.1

# stop the service and start it again
sudo systemctl restart ssh

# connect remotely to the Fedora
ssh alanyu@10.37.129.4

# On the Fedora system show that the file: website.app, has been created
echo "Hello Fedora" > website.app
ls -l website.app

# Transfer SSH Key Pair
ssh-copy-id -i ./.ssh/id_ed25519_chapter-9-lab.pub  alanyu@10.37.129.4

#SSH Using RSA Key to Fedora
ssh -i ~/.ssh/id_ed25519_chapter-9-lab.pub alanyu@10.37.129.4
echo "Hello Fedora RSA" > new-website.app
ls -l new-website.app





